package com.gmail.sharpcastle33.aspects;

public enum Aspect {
  
  MUNDANE_WATER,
  MUNDANE_LIFE,
  MUNDANE_DEATH,
  MUNDANE_AIR,
  MUNDANE_FIRE,
  MUNDANE_FROST,
  MUNDANE_EARTH,
  
  MUNDANE_ARCANE,
  MUNDANE_DIVINE,
  MUNDANE_CORRUPT,
  MUNDANE_VOID,
  MUNDANE_PSIONIC,
  MUNDANE_MECHANIC,
  MUNDANE_ESSENCE,
  
  CONCENTRATED_WATER,
  CONCENTRATED_LIFE,
  CONCENTRATED_DEATH,
  CONCENTRATED_AIR,
  CONCENTRATED_FIRE,
  CONCENTRATED_FROST,
  CONCENTRATED_EARTH,
  
  CONCENTRATED_ARCANE,
  CONCENTRATED_DIVINE,
  CONCENTRATED_CORRUPT,
  CONCENTRATED_VOID,
  CONCENTRATED_PSIONIC,
  CONCENTRATED_MECHANIC,
  CONCENTRATED_ESSENCE,
  
  PURE_WATER,
  PURE_LIFE,
  PURE_DEATH,
  PURE_AIR,
  PURE_FIRE,
  PURE_FROST,
  PURE_EARTH,
  
  PURE_ARCANE,
  PURE_DIVINE,
  PURE_CORRUPT,
  PURE_VOID,
  PURE_PSIONIC,
  PURE_MECHANIC,
  PURE_ESSENCE,

}
