package com.gmail.sharpcastle33.potions;

/**
 * Enum of all CustomPotions in AspectAlchemy
 */
public enum CustomPotion {	
	MUNDANE_POT,
	AEGIS_CORDIAL,
	DIVINES_KISS,
	FLAMEREND_PHILTER,
	FLAMEREND_ELIXIR,
	FLAMEBANE_STRONGBREW,
	VIGORINE_TONIC,
	VIGORINE_ELIXIR,
	VIGORINE_AERIFORM,
	STALWART_SPIRIT,
	SINEW_SPIRIT,
	FEATHERWEIGHT_PHILTER,
	SKYREACH_TONIC,
	POTENT_SKYREACH,
	LIQUID_LUCK,
	LIQUID_FORTUNE,
	DARKSIGHT_ELIXIR,
	BLESSING_OF_PROVIDENCE,
	SOULBOND,
	FLEETSWIFT_PHILTER,
	FLEETSWIFT_STRONGBREW,
	AUGA_EUPNEA,
	
	BLIGHTBLOT,
	POTENT_BLIGHTBLOT,
	SCOURGE,
	SOMNOLENT,
	SOMNOLENT_STRONGBREW,
	SPORIFINE,
	SOULREND,
	COGENT_SOULREND,
	SOULBANE,
	
	BLESSING_OF_VIGOR,
	SOUVINERINE,
	FIREREND_SINEW,
	AEGIS_CELESTIAL,
	
	DEVILS_KISS,
	DEATHBRINGER,
	
	ANTIDOTE,
	POTENT_ANTIDOTE,
	VITARUN_ELIXIR,
	
	DEBUG_POTION
} // enum
