package com.gmail.sharpcastle33.potions;

/**
 * Enum of all CustomPotions in AspectAlchemy
 */
public enum CustomPotion {
	MUNDANE_POT, 
	HEALTH_TINCTURE, 
	HEALTH_VIAL, 
	FIREBALL, 
	FREEZE,
	LEVITATION_VIAL,
	FIREBANE_ELIXIR,
	LIQUID_LUCK,
	HEALTH_TWO_SPLASH,
	SPEED_TWO,
	SPEED_TWO_EXTENDED,
	FIRE_RESISTANCE,
	SPLASH_POISON,
	SPLASH_POISON_TWO,
	SPLASH_SLOWNESS,
	SPLASH_WEAKNESS,
	SPLASH_PLAGUE,
	MOONLIGHT_ELIXIR,
	SANGUINE_SUNSET_DRAUGHT,
	BLOODMOON_BRANDY,
	DEATHHEART_STRONGBREW
} // enum
