name: Alchemy
version: 1.12
author: Sharpcastle33
main: com.gmail.sharpcastle33.AspectAlchemy
commands:
    getpotion:
        description: (DEBUG) Gets a potion from AspectAlchemy
        usage: /getpotion <CUSTOMPOTION>
    getrecipe:
        description: (DEBUG) Gets the minimum recipe for a potion from AspectAlchemy
        usage: /getrecipe <CUSTOMPOTION>
    listpots:
        description: (DEBUG) Lists all potions loaded from the potions.yaml
        usage: /listpots
    gettools:
        description: (DEBUG) Gets all debug admin tools
        usage: /gettools
